### PR TITLE
Views for cluster and track

### PR DESCRIPTION
**Pull request by brauliorivas**
BEGINRELEASENOTES
- Following #43, `Cluster` and `Track` collections now have a view for the visualizations. 
- It is known that `Cluster` has a relation with: other `Cluster`s, `MCParticle`, and `RecoParticle`. Currently, only there are two views for the first two. 
- I've assumed that views with objects of the _**same type**_ will be a `tree` (because the current views work the same way e.g. MCParticle or ReconstructedParticle). That's why now `Track` and `Cluster` do the same algorithm to be placed on eede. I've also assumed that when the view is to show an `association`, it's shown vertically, just like on the previous PR (e.g. MCRecoAssociation). So the view for `MCTrack` and `MCCluster` associations are the same (each object placed vertically). 
- The same progress described above applies for `Track`. 

ENDRELEASENOTES

Hey @tmadlener, @kjvbrt, what pattern/design/way would you like to show the view for relations between `Cluster`-`RecoParticle`, and `Track`-`RecoParticle`. I was thinking to do it like associations (vertically), but to show on the left side the `RecoParticle`, and on the right side, a branch of related `Cluster` or `Track` (depending of the relation). Also, what information/properties should be displayed for `Track` and `Cluster`?
image
(the same logic would apply for track)

Missing: I still haven't changed the colors/shape of the different objects (as discussed with mentors).  
Note: I have to test this with other generated events (the test file doesn't have this data). But in theory, this should work fine.

### CODE REVIEW

**Comment by kjvbrt** [comment]
Hi @brauliorivas, for the cluster I would say Type, energy and position (for the cluster I would keep it split into x, y, and z)
With the track parametrization I'm not that familiar, but let's say for the start: type, chi2 / ndf (separate, but on one line), dEdx, and number of trackerHits.

**Comment by kjvbrt** [comment]
> Hey @tmadlener, @kjvbrt, what pattern/design/way would you like to show the view for relations between Cluster-RecoParticle, and Track-RecoParticle. I was thinking to do it like associations (vertically), but to show on the left side the RecoParticle, and on the right side, a branch of related Cluster or Track (depending of the relation).

I thing what is proposed in the drawing is a good start, but if you find out that it is overly complex to have it this way, feel free to ditch it. Maybe horizontal ordering will be easier to implement? I would not spend too much time in searching for the best one at this point :)

**Comment by tmadlener** [comment]
I think we could also have the `ReconstructedParticle` - `Track` and `ReconstructedParticle` - `Cluster` view merged into one, since usually a reco particle has not too many tracks and clusters (I would say it's either only a Cluster or a Cluster and a Track or only a Track in most cases).

If it's possible we could also have an "interactive view" that starts from a list of e.g. `ReconstructedParticle`s and then if I click on one, it "explodes" that one into a view where all the related objects pop up. and then users could click on one of the new boxes and the same happens for that. Not sure yet what the layout would be for that, but also this would not be part of this PR in any case.

**Comment by brauliorivas** [comment]
> If it's possible we could also have an "interactive view" that starts from a list of e.g. `ReconstructedParticle`s and then if I click on one, it "explodes" that one into a view where all the related objects pop up. and then users could click on one of the new boxes and the same happens for that. Not sure yet what the layout would be for that, but also this would not be part of this PR in any case.

Very nice feature. Definitely taking this into account.

**Pull request merged**
